apiVersion: v1alpha
kind: cypress
framework: cypress
sauce:
  region: us-west-1
  metadata:
    tags:
      - e2e
      - release
    build: "build-1234"
rootDir: ./cypress
cypress:
  version: 9.7.0
  configFile: cypress.json
suites:
  - name: "Example Suite"
    browser: chrome
    config:
      platformName: Windows 10
      browserVersion: latest
      testFiles:
        - "cypress/*.spec.js"
